# Generated by Django 4.2.17 on 2025-03-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="file",
        ),
        migrations.RemoveField(
            model_name="document",
            name="size",
        ),
        migrations.AddField(
            model_name="document",
            name="file_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="s3_key",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="document",
            name="title",
            field=models.CharField(
                blank=True, default="Untitled Document", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="category",
            field=models.CharField(
                choices=[
                    ("LICENSE", "License"),
                    ("PASSPORT", "Passport"),
                    ("INVOICE", "Invoice"),
                    ("CHECK", "Check"),
                    ("RESUME", "Resume"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
