# Generated by Django 4.2.17 on 2025-03-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_remove_document_file_remove_document_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="category",
            field=models.CharField(
                choices=[
                    ("LICENSE", "License"),
                    ("PASSPORT", "Passport"),
                    ("INVOICE", "Invoice"),
                    ("CHECK", "Check"),
                    ("RESUME", "Resume"),
                ],
                default="OTHER",
                max_length=50,
            ),
        ),
    ]
