# Generated by Django 4.2.17 on 2025-03-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_alter_document_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="category",
            field=models.CharField(
                choices=[
                    ("License", "License"),
                    ("Passport", "Passport"),
                    ("Invoice", "Invoice"),
                    ("Check", "Check"),
                    ("Resume", "Resume"),
                ],
                default="OTHER",
                max_length=50,
            ),
        ),
    ]
