# Generated by Django 4.2.17 on 2025-03-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_documentinformation"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(
                default=0.00025983667409057166, upload_to="documents/"
            ),
            preserve_default=False,
        ),
    ]
