# Generated by Django 5.2 on 2025-06-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("Review", "Review"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Review",
                max_length=50,
            ),
        ),
    ]
